### ISSUE TITLE
No such file or directory?

### ISSUE THREAD

**Issue by shaupage92** [monfresh/laptop#10]
I encountered the following issues:

    Installing Homebrew ...
    curl: (6) Could not resolve host: raw.githubusercontent.com

    Updating Homebrew formulas ...
    mac: line 135: brew: command not found
    failed

    Users/XXXX/.rvm/scripts/rvm: No such file or directory

Something to note is that my internet connection went out during the install so I think that could have hurt the download process. How could I re-install the script then?

**Comment by monfresh** [comment]
Yep, that's what happened. `Could not resolve host` means it was not able to connect.

To re-install, simply run the script again :) In other words, run this again:
```
bash mac 2>&1 | tee ~/laptop.log && source ~/.rvm/scripts/rvm
```

The script is safe to run over and over. It will install what you don't already have, and it will skip what you already have. It will also check to see if what you have is out of date, and if so, it will update to the new version. I personally run the script regularly, maybe once a week or every two weeks or so to keep everything up to date.

**Comment by shaupage92** [comment]
Cheers!!
