### ISSUE TITLE
Not an issue, a question

### ISSUE THREAD

**Issue by anthonybrown** [monfresh/laptop#18]
I set my new MBP up already with Homebrew, RVM, postgresql, nginx, mongodb and things seem to be running as expected. when I run brew services list I get all the services running:
`Name       Status  User      Plist
memcached  started tonybrown /Users/tonybrown/Library/LaunchAgents/homebrew.mxcl.memcached.plist
mysql      started tonybrown /Users/tonybrown/Library/LaunchAgents/homebrew.mxcl.mysql.plist
nginx      started tonybrown /Users/tonybrown/Library/LaunchAgents/homebrew.mxcl.nginx.plist
php56      started tonybrown /Users/tonybrown/Library/LaunchAgents/homebrew.mxcl.php56.plist
postgresql started tonybrown /Users/tonybrown/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
redis      started tonybrown /Users/tonybrown/Library/LaunchAgents/homebrew.mxcl.redis.plist`

I was thinking of using your script ( first I wanted to use thoughtbots laptop script but liked the looks of this one)

Can I just run your script and will it overwrite my installs or should I start clean?
If starting clean, should I reinstall Yosemite or El Capitan, or is there a better way?

Thanks

**Comment by monfresh** [comment]
Hi @anthonybrown. You can run my script at any time. It won't overwrite anything. It only installs stuff you don't already have. If you already have something, and if it's up to date, it will skip it. Otherwise, it will upgrade it to the latest version.

The script also adds some stuff to you `.zshrc

**Comment by anthonybrown** [comment]
@monfresh thanks so much, I'll look over the code to see what's it's going to overwrite in my ~/.zshrc file.
Everything seems to working fine except my `airline vim` which doesn't show the git branch and other information.
