### ISSUE TITLE
Error: No available Cask for github.

### ISSUE THREAD

**Issue by roberthull** [monfresh/laptop#19]
Hi, I'm having some problems running your script in Terminal. I managed to get it to work fine up until this point:

===

Installing github...
==> We need to make Caskroom for the first time at /opt/homebrew-cask/Caskroom
==> We'll set permissions properly so we won't need sudo in the future
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
Error: No available Cask for github. Did you mean one of:
github-desktop
githubpulse

Error: nothing to install
failed

===

I couldn't find anything online about this to try and fix it, so I really have no clue what to do. Also, I ended up quitting Terminal and then re-opening it, and now Terminal launches with this message:

===

Last login: Mon Oct 19 08:56:55 on console
login(15426,0x7fff73e03300) malloc: *** error for object 0x7fbc90d12dc0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
        
[Process completed]

===

And I can't seem to enter anything into the window. I'm not sure if I screwed something up along the way, but any help would be much appreciated!

**Comment by monfresh** [comment]
Thanks for the report. The issue with the GitHub app is that the Cask has been renamed from `github` to `github-desktop`. The script uses [Homebrew Cask](http://caskroom.io/search) to install Mac apps, and the person/people who were maintaining the GitHub for Mac app renamed the app to `github-desktop`. Unfortunately, there's no way for me to be alerted to such changes in advance. I will submit a fix for this soon.

As for your Terminal error, I don't know what is causing it. I would try restarting your computer.

**Comment by roberthull** [comment]
Ok, thanks so much! I'll see if I can fix that Terminal error and retry it.
