### ISSUE TITLE
debugging for github part

### ISSUE THREAD

**Issue by aciccone1216** [monfresh/laptop#21]
Here is the error I received in my terminal (its at the bottom). I than download the github application manually and put my login information in but still received the same message. Thanks for the help!

Homebrew already installed. Skipping ...

Updating Homebrew formulas ...
Already up-to-date.

Already using the latest version of git. Skipping ...

Already using the latest version of postgresql. Skipping ...

Restarting postgres...
Stopping `postgresql`... (might take a while)
==> Successfully stopped `postgresql` (label: homebrew.mxcl.postgresql)
==> Successfully started `postgresql` (label: homebrew.mxcl.postgresql)

Already using the latest version of phantomjs. Skipping ...

Already using the latest version of hub. Skipping ...

Already using the latest version of RVM. Skipping...

Updating Rubygems...
Latest version currently installed. Aborting.
bundler (1.10.6)

Updating bundler ...
Updating installed gems
Nothing to update

Configuring Bundler ...
Your application has set jobs to "3". This will override the global value you are currently setting

Already using the latest version of heroku-toolbelt. Skipping ...

Already using the latest version of brew-cask. Skipping ...

flux is already installed. Skipping...

github-desktop is already installed. Skipping...

sublime-text3 is already installed. Skipping...
The file /Users/bonobos/Applications/GitHub.app does not exist.
failed

[19:37:45] ~
// ♥

**Comment by monfresh** [comment]
Thanks for the report. I just fixed this. Please pull the latest version and try again.
