### ISSUE TITLE
Laptop Installation Script

### ISSUE THREAD

**Issue by kimotion426** [monfresh/laptop#4]
Hi, I'm really sorry to bother you but I'm a total novice to this.  I tried running your script as directed but I don't know what the password is, and I keep getting this message:

Changing shell for Kim.
Password for Kim: 
chsh: Credentials could not be verified, username or password is invalid.  Credentials could not be verified, username or password is invalid.
failed

-bash: /Users/Kim/.rvm/scripts/rvm: No such file or directory
Kims-MacBook-Pro:~ Kim$ 

Could you please give me some advice on what I'm doing wrong?

**Comment by monfresh** [comment]
Hi @kimotion426. You're not bothering me at all. Thanks for trying out my script. I'll be glad to help you.

The password is your Mac password. It's the same one that you use to log in to your Mac. You can read more detailed instructions and watch a video here: https://github.com/monfresh/laptop/wiki/Detailed-installation-instructions-with-video

**Comment by monfresh** [comment]
I'm closing this, assuming you were able to get it working. If not, feel free to ask me for more help.
