### ISSUE TITLE
Ruby Version Alias

### ISSUE THREAD

**Issue by Swampgirl** [monfresh/laptop#52]
RESOLVED

Hi Monfresh,
How do I reverse the ruby version hub alias back to my original terminal prompt? 

Also, I am finding that I cannot cut and paste commands into my terminal window as I once did. If the terminal window is relatively small, the commands (usually the beginning), are cut off - so only the latter portion of the command shows up. If I expand the window manually, I can copy and paste commands without incident.
Before I installed your laptop script, there were no, in effect, "margins" limiting my cut and paste input into terminal.  How do I modify this new limitation?

I wish my actual age reflected the newness of my computer proficiency.  :)

Thank you for your script and your help.
Best Regards, Swampgirl

**Comment by Swampgirl** [comment]
Hi Monfresh!
I figured everything out - all guesswork, but all is okay and/or back to what it was before I made changes. There were no "margin" limitations in Terminal - I was not cutting and pasting Commands from a direct source; multi-line copying from Text Edit was my mistake.

**Comment by monfresh** [comment]
I'm glad you figured it out. Let me know if you have any other questions.
