### ISSUE TITLE
Installing via Fish Command Shell

### ISSUE THREAD

**Issue by deandavidbrittain** [monfresh/laptop#56]
<img width="839" alt="Screen Shot 2020-02-11 at 1 23 44 PM" src="https://user-images.githubusercontent.com/21200607/74275777-bc584a00-4cd1-11ea-97fc-b2a95c14ee39.png">

I'm having an issue installing this script via fish. I actually ran this install via zsh and it works great. My problem is though that for whatever reason while I'm in fish, I'm unable to use Jekyll even after installing it multiple times. . I wanted to try installing it again via fish to see if that would fix the issue. Any advice?

**Comment by monfresh** [comment]
Hi @deandavidbrittain. I use fish myself, but I haven't had the time to update this script to work with it yet. In the meantime, I believe you should be able to run the commands listed here: https://github.com/monfresh/laptop/blob/master/laptop

Alternatively, I have a separate more minimal script that supports fish: https://github.com/monfresh/install-ruby-on-macos

Also, if you can show me the error messages you get while trying to use Jekyll in fish, I can try to help.

**Comment by deandavidbrittain** [comment]
Hello @monfresh !! 

Thanks for the response and the other scripts I can try. Honestly, I have no idea how I got it to work, but I was able to solve my issue. I think I needed to reinstall ruby?? I’m unsure. 

Next time I setup my environment, I’ll check out these other scripts you provided. Thanks again!
