### ISSUE TITLE
SIGILL: illegal instruction

### ISSUE THREAD

**Issue by primehalo** [monfresh/laptop#57]
I just installed this on my macOS High Sierra 10.13.6 and now every time I open a terminal I see this:

```
Last login: Sun Jun 14 14:01:12 on ttys000
SIGILL: illegal instruction
PC=0x1065350 m=0 sigcode=1

goroutine 1 [running, locked to thread]:
runtime.asyncPreempt()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/preempt_amd64.s:8 fp=0xc00003cef0 sp=0xc00003cee8 pc=0x1065350
fmt.init()
	/usr/local/Cellar/go/1.14/libexec/src/fmt/scan.go:465 fp=0xc00003cef8 sp=0xc00003cef0 pc=0x10df3a0
runtime.doInit(0x1687960)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5414 +0x8a fp=0xc00003cf28 sp=0xc00003cef8 pc=0x1042a2a
runtime.doInit(0x168c1c0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00003cf58 sp=0xc00003cf28 pc=0x10429f7
runtime.doInit(0x16866a0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00003cf88 sp=0xc00003cf58 pc=0x10429f7
runtime.main()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:190 +0x1ce fp=0xc00003cfe0 sp=0xc00003cf88 pc=0x1035f0e
runtime.goexit()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00003cfe8 sp=0xc00003cfe0 pc=0x1063af1

rax    0x1687960
rbx    0xb
rcx    0x0
rdx    0x16879b8
rdi    0xc000090210
rsi    0x10df3a0
rbp    0xc00003cf18
rsp    0xc00003cee8
r8     0x11
r9     0x11
r10    0x14631c4
r11    0x1
r12    0xffffffffffffffff
r13    0x22
r14    0x21
r15    0x200
rip    0x1065350
rflags 0x10202
cs     0x2b
fs     0x0
gs     0x0
[~] ruby 2.7.1p83 $ 
```
Also, during install I had kept the BASH shell but said YES to showing the current directory and ruby version. How can I now disable those features so it looks like it used to? It seems that when the currently directory path is long it doesn't looks weird.

**Comment by monfresh** [comment]
Hi @primehalo. Sorry for the late reply. This got lost in my email. The errors you posted look like they are related to Golang. Do you perhaps have some Golang-related stuff in your `~/.bashrc` or `~/.bash_profile`?

As for removing the current directory, you can remove these lines from your `~/.bash_profile`:
```bash
prompt_ruby_info() {
  echo $(ruby -v | grep -o 'ruby [^\( ]*')
}
```

**Comment by primehalo** [comment]
I'm unfamiliar with Golang, but I can't say for sure that it's not installed (whatever it is). This Mac isn't my primary machine, I basically only use it for app development. I don't see a .bashrc file and don't see anything saying golang in my .bash_profile file. This is what my .bash_profile looks like after removing those lines you mentioned:
```
alias laptop='bash <(curl -s https://raw.githubusercontent.com/monfresh/laptop/master/laptop)'

export PATH="$HOME/.bin:$PATH"

export PATH="/usr/local/bin:$PATH"

eval "$(hub alias -s)"

source /usr/local/share/chruby/chruby.sh

source /usr/local/share/chruby/auto.sh

chruby ruby-2.7.1

GREEN=$(tput setaf 65)

ORANGE=$(tput setaf 166)

NORMAL=$(tput sgr0)

export CLICOLOR=1;

export LSCOLORS=exfxcxdxbxegedabagacad;
```

**Comment by monfresh** [comment]
It looks like this is an issue with the Homebrew version of `hub`: https://github.com/github/hub/issues/2512
You can fix that by either upgrading hub via `brew upgrade hub` or by removing `eval "$(hub alias -s)"` from your `.bash_profile` if you don't use `hub`.

**Comment by primehalo** [comment]
Thanks. I first tried the update but that didn't fix it so I removed the line from .bash_profile and that fixed it. I don't ever recall installing hub (still not even sure what it's used for) but I guess I must have at some point.

**Comment by monfresh** [comment]
This script was installing `hub`, but I just replaced it with the better GitHub CLI, which doesn't require adding anything to your shell file.
