### ISSUE TITLE
laptop script not creating or finding .rubies folder

### ISSUE THREAD

**Issue by liaprins** [monfresh/laptop#60]
I love the blog post you wrote about installing ruby for Jekyll via a script, but alas if it could only work for me. I had to first fix several errors that kept cropping up every time I ran it, but at last there are not more errors in the log that I can fix. It just says that it cannot find the .rubies folder (and I checked, it's not there; I tried to create one manually but my Mac won't let me make folders that start with a "."). 

I would love to help fix / troubleshoot this except I am at the limits of my knowledge in this area, but please let me know if I can test anything you have in mind that might work, as I am desparate to be able to get Jekyll set up as soon as I can! (Or if you think I should try a different tactic than the scripts? (I have tried both of your scripts with same issue.)) 

I am running macOS Catalina, version 10.15.7 (19H15)

[laptop.log](https://github.com/monfresh/laptop/files/5657131/laptop.log)

**Comment by monfresh** [comment]
Hi @liaprins. Thanks for reading my blog post and trying out my script. I'd be glad to help you. Do you recall by any chance the first errors you had to fix? It's mainly for my curiosity and to document it for others who might be in the same situation as you.

Let's try this for now. We will uninstall and reinstall chruby and ruby-install:

```shell
brew uninstall chruby ruby-install
```
and then

```shell
brew install chruby ruby-install
```
and then we'll install the latest Ruby:

```shell
ruby-install ruby
```
The Ruby installation takes a few minutes. Once it's done, quit and relaunch Terminal, then check the ruby version:
```shell
ruby -v
```
If it doesn't say `ruby-2.7.2`, try switching to it manually:
```shell
chruby 2.7.2
```
Then check the version again:
```shell
ruby -v
```

Let me know if that works and then we'll go from there.

**Comment by liaprins** [comment]
Thank you for your help! That was so close to working. The newer 2.7.2 ruby installed, but before that, when I ran the `brew install chruby ruby-install` the terminal gave me these messages:

**Add the following to the ~/.bash_profile or ~/.zshrc file:
  source /usr/local/opt/chruby/share/chruby/chruby.sh**

**To enable auto-switching of Rubies specified by .ruby-version files,
add the following to ~/.bash_profile or ~/.zshrc:
  source /usr/local/opt/chruby/share/chruby/auto.sh**

So I found the `usr` folder it was referring to (I had about 8 `usr` folders on my machine, but this one had the sub-folders it wanted), but it already had both the chruby.sh and the auto.sh files inside, so I did not do anything.

So then I ran the `ruby-install ruby` command and it said 
**Successfully installed ruby 2.7.2 into /Users/lprins/.rubies/ruby-2.7.2**. 

But then when I ran `ruby -v` it says: **ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]**

So I tried the `chruby 2.7.2` command, and it said
**-bash: chruby: command not found**

**Comment by liaprins** [comment]
Also, I just tried running the `laptop` script again in case the logs it produced would help, but mysteriously it did the seemingly successful "**All done!**" message... so I tried `chruby 2.7.2` again, but unfortunately it just still says "**-bash: chruby: command not found**" :(

Attaching the latest laptop.log file in case it has any clues anyway.
[laptop.log](https://github.com/monfresh/laptop/files/5661004/laptop.log)

**Comment by liaprins** [comment]
Also, since you wanted to know about the errors I was first getting with the laptop script yesterday, I don't remember all of them, but for some I took screenshots so it was easier to follow what they said. So I am attaching those screenshots here.
![Screen Shot 2020-12-07 at 8 26 22 PM](https://user-images.githubusercontent.com/17435353/101525086-ab9f5180-393f-11eb-9b52-64fc78a9a368.png)
![Screen Shot 2020-12-07 at 8 27 20 PM](https://user-images.githubusercontent.com/17435353/101525092-acd07e80-393f-11eb-9abd-ad25629192e7.png)
![Screen Shot 2020-12-07 at 8 27 30 PM](https://user-images.githubusercontent.com/17435353/101525096-ad691500-393f-11eb-8b7c-5829d49a354d.png)

**Comment by monfresh** [comment]
Thanks! Can you try opening a new Terminal tab or quitting and restarting Terminal? The Terminal has to be "refreshed" after making changes like the ones the script makes.

If that doesn't work, could please paste the output of this command?

```shell
cat ~/.bash_profile
```
And this command too please:

```shell
brew list
```

**Comment by liaprins** [comment]
Okay great, here is the output of **cat ~/.bash_profile**:

```
#Bash
alias brc='vi ~/.bash_profile'
alias sb='source ~/.bash_profile'
# Navigation
alias lr='ls -lGthr'
alias ll='ls -lGh'
alias ls='ls -G'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias cd..='cd ..'

# Can't Spell
alias ci='vi'
alias vo='vi'
alias gti='git'

# cxg e2e
export JEST_ENV="dev"
export JEST_CXG_PORT=3000

# python
# Set python3 as "default" python
alias pip='pip3'
alias python='python3'

#VIRTUAL ENVS
ve () {
        mkdir -p venvs
        MYVENV=venvs/${1:-venv}
        python3.7 -m venv $MYVENV
        source $MYVENV/bin/activate
}

destroy () {
        V_PATH=$VIRTUAL_ENV
        if [[ $V_PATH != "" ]]
        then
                deactivate
                rm -rf $V_PATH
        fi
}
# Setting PATH for Python 3.7
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.7/bin:${PATH}"
export PATH
# added by Anaconda3 2019.10 installer
# >>> conda init >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$(CONDA_REPORT_ERRORS=false '/Users/lprins/opt/anaconda3/bin/conda' shell.bash hook 2> /dev/null)"
if [ $? -eq 0 ]; then
    \eval "$__conda_setup"
else
    if [ -f "/Users/lprins/opt/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/lprins/opt/anaconda3/etc/profile.d/conda.sh"
        CONDA_CHANGEPS1=false conda activate base
    else
        \export PATH="/Users/lprins/opt/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda init <<<

# Path modifications
export PATH="~/.bin:$PATH"
eval "$(ssh-agent -s)"
export PATH="$HOME/.gem/ruby/2.6.0/bin:$PATH"

alias laptop='bash <(curl -s https://raw.githubusercontent.com/monfresh/laptop/master/laptop)'

export PATH="$HOME/.bin:$PATH"

```


And here is the output of **brew list**:
```

autoconf	gdbm		heroku		libffi		postgresql
automake	gettext		heroku-node	libyaml		readline
bison		gh		icu4c		openssl@1.1	ruby
chruby		git		krb5		pcre2		ruby-install
```

**Comment by liaprins** [comment]
UPDATE: I just realized I think I may have misunderstood the following messages from my terminal that I mentioned intially:

**Add the following to the ~/.bash_profile or ~/.zshrc file:
source /usr/local/opt/chruby/share/chruby/chruby.sh**

**To enable auto-switching of Rubies specified by .ruby-version files,
add the following to ~/.bash_profile or ~/.zshrc:
source /usr/local/opt/chruby/share/chruby/auto.sh**

All I did was navigate into the folder where chruby.sh and auto.sh were, intending to manually add empty files there (Ithought that's what the message said to do), but the files were already there so I did nothing. But looking closer, it says to _add_ them to  the ~/.bash_profile, which I did not do... I do not even really know what it means? I am going to continue researching on the internet more about how, but if you see this comment from me, do you think my not having done this is the issue, and doing it will fix the problem? If so, how do I "add" source /usr/local/opt/chruby/share/chruby/chruby.sh to "the ~/.bash_profile" ? Thank you immensely!!!!!!!!

**Comment by monfresh** [comment]
I was just typing when I saw your latest message come in. Yes, that is exactly the issue. You helped me discover a bug. Your `~/.bash_profile` is missing those lines. The script only adds them there if you don't already have `chruby` and `ruby-install`, and since we installed those manually, and then ran the script again, the script didn't add those lines.

When you see a message that says to add something to ~/.bash_profile, that means copy and paste that line in the file called `.bash_profile` that's in your macOS Home folder, which is represented by the `~`, which is a shortcut for the Home folder, which is `/Users/lprins`.

There are two ways to add a line to a file. You can use this command, which will automatically add it to the file without you having to open it in a text editor:

echo 'source /usr/local/share/chruby/chruby.sh' >> ~/.bash_profile
echo 'source /usr/local/share/chruby/auto.sh' >> ~/.bash_profile

Note that the lines you mentioned are different from the ones in the `echo` commands above. I'm pretty sure what you want is what I pasted above.

The other way to edit the `.bash_profile` is to run `open ~/.bash_profile`, which will open it in TextEdit, and then you can copy and paste the lines at the end of the file, and then save it. Then to "refresh it", you can run `source ~/.bash_profile` or `sb` because it looks like you have a shortcut for that already defined in your .bash_profile.

Also, I would remove this line from your `.bash_profile`: `export PATH="$HOME/.gem/ruby/2.6.0/bin:$PATH"`
as well as the very last line you had there: `export PATH="$HOME/.bin:$PATH"`

Here's an article I wrote about how to read and edit hidden files (those that start with a dot): https://www.moncefbelyamani.com/5-ways-to-open-hidden-files-on-your-mac/

**Comment by monfresh** [comment]
And I would also run `brew uninstall ruby`. Since Ruby is being managed by chruby, it's best to not have other Ruby installations that could potentially interfere with it.

**Comment by liaprins** [comment]
Thank you, I am about to try all of this now!

**Comment by liaprins** [comment]
YES YES YES, this seems to have worked! Now I am getting the ruby version to be 2.7.2 after doing what you described + restarting Terminal + changing to that version via chruby! Thank you so so much for your swift and speedy and thorough help! 
🤩 💪 🦄 🦎 🥨 ❗️

**Comment by monfresh** [comment]
You're welcome! Another thing I forgot to mention that's worth adding to your `.bash_profile` is this line at the end:
```
chruby ruby-2.7.2
```
That way, whenever you `cd` into a new directory, you will always have that Ruby version. Remember to run `sb` to refresh after you add that line.

**Comment by liaprins** [comment]
Okay great I have added it! thank you so much for all of your personalized help, I really really really appreciate it! And am looking forward to forthcoming blog posts of yours!!!
