### ISSUE TITLE
fails when updating rubygems

### ISSUE THREAD

**Issue by zaphod-bbrox** [monfresh/laptop#63]
Hi Monfresh,
I'm slightly out of my depth, but that's not entirely unusual for me.
Anyway I can't figure out exactly what's causing the script to fail when updating rubygems.
I'm sure the issue will lie with something I have done, and not your script.

Here's the log, if you have time to check it out:

------
Welcome to the monfresh laptop script!

You should be and up and running with a working Ruby environment in a few minutes.

The following lines are to help me debug any issues:

Current shell: /bin/zsh.

Homebrew already installed. Skipping ...

Verifying the Homebrew installation...
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/martin/.pyenv/shims/python3.6m-config
  /Users/martin/.pyenv/shims/python-config
  /Users/martin/.pyenv/shims/python3-config
  /Users/martin/.pyenv/shims/python3.6-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libwkhtmltox.0.12.5.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h

Your Homebrew installation reported some errors or warnings.
Review the Homebrew messages to see if any action is needed.

Installing formulas and casks from the Brewfile ...
Updating Homebrew...
Using git
Using heroku/brew
Using heroku
Using homebrew/services
Using postgresql
Using gh
Homebrew Bundle complete! 6 Brewfile dependencies now installed.

All formulas and casks were installed successfully.
Using chruby
Using ruby-install
Homebrew Bundle complete! 2 Brewfile dependencies now installed.

Checking if a newer version of Ruby is available...

You have the latest version of Ruby

Updating Rubygems...
ERROR:  Loading command: update (LoadError)
	cannot load such file -- openssl
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
failed

**Comment by monfresh** [comment]
Hi @zaphod-bbrox. What you are running into is a common issue that happens around the time that Apple releases a new macOS update. Sometimes, the command line tools don't get updated. If you look towards the top of the log, you'll see this message:
```
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
softwareupdate --all --install --force

If that doesn't show you an update run:
sudo rm -rf /Library/Developer/CommandLineTools
sudo xcode-select --install
```
This is what I usually do:
1. First, I try installing the latest update from the Software Update section in System Preferences, and I restart the computer
2. Then I open my terminal application, and I check if Homebrew is happy:
    ```shell
    brew doctor
    ```
3. If it still gives the same message as before, then I try the command it suggests:
    ```shell
    softwareupdate --all --install --force
    ```
4. If that doesn't prompt to download or install tools, then I delete the tools and reinstall them, like Homebrew suggests:
    ```shell
    sudo rm -rf /Library/Developer/CommandLineTools
    sudo xcode-select --install
   ```
Then, check that the tools are found with `brew doctor`, and if they are, run my script again.
Let me know if that works.

**Comment by monfresh** [comment]
To clarify, I don't mean to install Big Sur if you are on Catalina. This is for the incremental updates within the same macOS version.

**Comment by zaphod-bbrox** [comment]
Thanks for that clarification and great help.
I am on Catalina, and am not quite ready to go to Big Sur.
But my Catalina is up to date.
I'll try those other suggestions, tomorrow, it's very late here so I will get back to you after some sleep. Thanks again.

**Comment by zaphod-bbrox** [comment]
Just confirming that I have tried all 4 steps you mentioned and I still have not had any change.
I see in another active thread you are looking into possible adjustments to the script, so I'll just put this aside for now.
Thanks for the help.

**Comment by monfresh** [comment]
@zaphod-bbrox The bug should be fixed now. Please try these steps:

1. Run `rm -rf ~/.rubies/ruby-2.7.2`
If it says "permission denied", try it with `sudo`:
```shell
sudo rm -rf ~/.rubies/ruby-2.7.2
```
If it says that the directory does not exist, or something like that, ignore it.

2. Then run the script again: 
```sh
bash <(curl -s https://raw.githubusercontent.com/monfresh/laptop/master/laptop)
```

**Comment by zaphod-bbrox** [comment]
I appreciate the help @monfresh. Unfortunately I'm getting a lot of errors on it now. I'm attaching the laptop.log.
It's most likely something I have done wrong previously.
[laptop.log](https://github.com/monfresh/laptop/files/5718950/laptop.log)

**Comment by monfresh** [comment]
Hi @zaphod-bbrox. It looks like something is wrong with the command line tools. Can you please try removing them and reinstalling them by running these 2 commands one by one:
```shell
sudo rm -rf /Library/Developer/CommandLineTools
sudo xcode-select --install
```
And then make sure that the tools are finished installing, and then restart your computer, then try the script again:
```shell
bash <(curl -s https://raw.githubusercontent.com/monfresh/laptop/master/laptop)
```
To help me debug, can you also please tell me what the output of these commands are?
```shell
brew list
```
and
```shell
brew outdated
```
Thanks!

**Comment by zaphod-bbrox** [comment]
brew list:

`autoconf	gettext		heroku		jpeg		libtiff		openssl@1.1	postgresql	ruby-install	xz
chruby		gh		heroku-node	krb5		node		pcre2		pyenv		sqlite		zlib
freetype	git		icu4c		libpng		nvm		pkg-config	readline	webp`

brew outdated:
`freetype (2.10.2) < 2.10.4
libtiff (4.1.0) < 4.1.0_1
node (14.12.0) < 15.4.0
nvm (0.35.3) < 0.37.2`

I reinstalled the command line tools as you said. Seems to have worked.
Now with the laptop script, I have the following permissions error:
`Updating Rubygems...
[laptop.log](https://github.com/monfresh/laptop/files/5720483/laptop.log)

ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.
Updating rubygems-update
failed`

laptop.log is attached (looks very different to last time).

**Comment by monfresh** [comment]
OK great! We're almost there. I just realized the bug with the tool I depend on to install Ruby was more serious than I thought. It's not installing certain prerequisites, but the good news is that I can specify them in my script, which I just did. So we're going to need to remove Ruby 2.7.2 again, and run the script one more time, and hopefully that should do it.

1. Run `rm -rf ~/.rubies/ruby-2.7.2`
If it says "permission denied", try it with `sudo`:
```shell
sudo rm -rf ~/.rubies/ruby-2.7.2
```
If it says that the directory does not exist, or something like that, ignore it.

2. Then run the script again: 
```sh
bash <(curl -s https://raw.githubusercontent.com/monfresh/laptop/master/laptop)
```

**Comment by zaphod-bbrox** [comment]
Fantastic, it worked! I got the All Done message.
Thanks so much for sticking with me on this one.

**Comment by monfresh** [comment]
Yay! Could you please confirm everything is working by quitting and restarting Terminal and following these steps:
https://github.com/monfresh/laptop#how-to-tell-if-the-script-worked

And then please confirm that you can install and use gems.

Also, you should now be able to just run `laptop` from your Terminal, and it should run the script again, and since you already have everything installed, it should finish faster and without any issues.

**Comment by zaphod-bbrox** [comment]
Thank you @monfresh.
Yes, can confirm I festarted Terminal, followed those steps in your link. All good
Can install gems.
Can run Laptop script successfully without any issues.
Thanks for your excellent help.
