### ISSUE TITLE
arch: Can't find nodenv in PATH

### ISSUE THREAD

**Issue by Nayrouz109** [monfresh/laptop#70]
Hey Moncef! 

When running the script `laptop` i get the following error:  

> Configuring Bundler ...
...Finished Ruby installation checks.
Installing node 14.15.3 ...
mac: line 308: nodenv: command not found
arch: Can't find nodenv in PATH
failed

I am working on macOS Big Sur (11.2.1) Intel Core

[laptop.log](https://github.com/monfresh/laptop/files/6020026/laptop.log)

Would appreciate any help! 

Thanks!

**Comment by monfresh** [comment]
Hi @Nayrouz109. I see that you have RVM installed. If you want to install Ruby with my script, you'll need to uninstall RVM by running this command:

```
rvm implode
```
And then open your `~/.bash_profile`:

```
open ~/.bash_profile
```
This should open it in TextEdit. Then, delete this line from the file:

```
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
```

Then save the file, and restart your computer.

Then try running my script again by running this command:

```
laptop
```

**Comment by Nayrouz109** [comment]
Thanks much @monfresh . it worked !

**Comment by monfresh** [comment]
Hi. I just noticed that you updated the title and issue. Next time, please add a new comment, because I wasn't sure if you posted the new laptop.log after you said everything worked.

According to the log, your command line tools are outdated and will not work in Big Sur. You'll need to update them:

```
sudo rm -rf /Library/Developer/CommandLineTools
```
Then:
```
sudo xcode-select --install
```

Then restart your computer, and run the script again.

**Comment by Nayrouz109** [comment]
Hi. I just updated the command line tools as you suggested. Thank you for your help!

**Comment by monfresh** [comment]
You're welcome! So, everything is working now? Did the script say "All done" at the end?

**Comment by Nayrouz109** [comment]
Yess! it says "All done" once the script ends. And when I check `ruby -v` it shows `ruby 3.0.0p0` Thank you! 

I will be following your guidelines on how to make Github Pages work with Jekyll and was wondering if it would be ok to ask questions if I run into errors or other issues? I would appreciate it.

**Comment by monfresh** [comment]
Yes, you can email me your questions. I'm glad it's all working now.
