### ISSUE TITLE
Help getting Ruby on MacOS w/ M1

### ISSUE THREAD

**Issue by leedc0** [monfresh/laptop#71]
[laptop.log](https://github.com/monfresh/laptop/files/6219186/laptop.log)
Hi! Before opening a new issue, please make sure it has not already been reported.

If you're on a Mac with the M1 chip, read this section:
https://github.com/monfresh/laptop/wiki/Troubleshooting-Errors#errors-on-macs-with-the-m1-chip

For all others Macs, please upload or paste the contents of the `laptop.log` file that's in your Home folder.

Thanks!

**Comment by leedc0** [comment]
I tried running the script a few weeks back and could figure it out. Started up again today, and I'm lost. I appreciate any assistance to get up and running has I've given my old laptop away and haven't been able to get back to learning ruby for some time.

**Comment by monfresh** [comment]
Hi @leedc0. It looks like there are a few things going on. The most important is that it seems like you are running your terminal in Rosetta mode. Is that right? If so, you do NOT need to do that. Homebrew supports the M1 chip natively. The second issue is that for some reason, Homebrew failed to update. Maybe there was a glitch.

Let's try this:

1. Make sure to quit Terminal and launch it again, but without Rosetta
2. Run my script again by running `laptop`.

**Comment by leedc0** [comment]
@monfresh, it worked. I definitely tried the standard Terminal and quit and launch, but this time it worked. However, this time after I re-launch, I ran the `clear` command, but the text was still there and then ran `laptop`. Thank you!
