### ISSUE TITLE
Unable to execute your script

### ISSUE THREAD

**Issue by novelmartis** [monfresh/laptop#74]
These are the contents of the laptop.log file

mac: line 15: /Users/novelmartis/.zshrc: Permission denied
failed

It seems there is a permissions issue however i am unable to figure out where the issue arises. Using sudo doesn't work either. What do you suggest I should do?

**Comment by monfresh** [comment]
Hi. Can you please run this command in your Terminal and paste the output?

```
ls -l ~/.zshrc
```

**Comment by novelmartis** [comment]
This is the output: -rw-r--r--  1 root  staff  446 May 23 23:29 /Users/novelmartis/.zshrc

**Comment by monfresh** [comment]
Try this:

```
chown $(whoami) ~/.zshrc
```

Then check again:

```
ls -l ~/.zshrc
```

It should say "novelmartis" instead of "root" (next to "staff").

If that didn't work, try it with `sudo`:

```
sudo chown $(whoami) ~/.zshrc
```

Then run my script again.

**Comment by novelmartis** [comment]
Worked like a charm. Thanks a lot!

So this was a permissions issue? That the root had permission but not the user?

**Comment by monfresh** [comment]
You're welcome! I'm glad it worked.

About the permissions, yes, that's correct. Normally, that file should have your user listed as the owner, but for some reason, it got assigned to `root`. Perhaps you created it manually? My script attempts to write to the `.zshrc` file, but any file that is owned by `root` needs extra permissions to be modified. One way to do that is to use `sudo`, but that's a potentially dangerous tool to use, so in this case, the best practice is to give the file the proper owner.
