### ISSUE TITLE
Ruby Error

### ISSUE THREAD

**Issue by alessandroseni** [monfresh/laptop#77]
[laptop.log](https://github.com/monfresh/laptop/files/7175189/laptop.log)
Hi! Before opening a new issue, please make sure it has not already been reported.

If you're on a Mac with the M1 chip, read this section:
https://github.com/monfresh/laptop/wiki/Troubleshooting-Errors#errors-on-macs-with-the-m1-chip

For all others Macs, please upload or paste the contents of the `laptop.log` file that's in your Home folder.

Thanks!

**Comment by monfresh** [comment]
Hello @alessandroseni.

The script detected that you have `rbenv` installed, but my script is not compatible with rbenv, as mentioned in my guide. You'll first need to uninstall rbenv using these instructions:
https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/#uninstall-rbenv

I just realized that my guide doesn't show people how to check if rbenv and rvm are already installed. I will update it.

**Comment by monfresh** [comment]
Hello @alessandroseni. Have you had a chance to uninstall rbenv and try again?

**Comment by alessandroseni** [comment]
Moncef,

I did uninstall and it worked! Thank you so much, your guide truly helped me.

Alessandro Seni
***@***.***

**Comment by monfresh** [comment]
Great! You're welcome.
