### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by Nightcrawler215** [monfresh/laptop#8]
I am admittedly incredibly novice. When I try to install I get this error. 

Installing bundler ...
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.
failed.

How do I gain permission to install?

**Comment by monfresh** [comment]
Hi. Thanks for the report. Can you please attach your `laptop.log` file that was created in your home folder? Also, what version of OS X are you using?

**Comment by Nightcrawler215** [comment]
I am currently using Mavericks. Here is the log file.


Homebrew already installed. Skipping ...

Updating Homebrew formulas ...
Already up-to-date.

Already using the latest version of git. Skipping ...

Already using the latest version of postgresql. Skipping ...

Restarting postgres...
Stopping `postgresql`... (might take a while)
==> Successfully stopped `postgresql` (label: homebrew.mxcl.postgresql)
==> Successfully started `postgresql` (label: homebrew.mxcl.postgresql)

Already using the latest version of qt. Skipping ...

Already using the latest version of hub. Skipping ...

Already using the latest version of RVM. Skipping...

Updating Rubygems...
Latest version currently installed. Aborting.

Installing bundler ...
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.
failed


Sorry for the wall of text. It said that the file needed to be png, gif, or jpg. As I am sure you know the file was log. If there is another I can upload this I would be more than happy to do it. Sorry if this sounds ignorant as hell I am very green to this field.

**Comment by monfresh** [comment]
I think there might be an issue with RVM. I tested the script on Mavericks a few days ago, so I'm not sure why it's failing now. I think the issue is that RVM did not install Ruby.

If you run `rvm list rubies`, does it say:
```
# No rvm rubies installed yet. Try 'rvm help install'.
```

If so, please try the following and let me know if it works:

1. Quit and relaunch Terminal
2. Run `rvm install 2.2.1`
3. Run `rvm --default use 2.2.1`
4. Run `bash mac 2>&1 | tee ~/laptop.log`

**Comment by nates-r7** [comment]
I had the same error. When I tried the steps listed above from @monfresh, everything worked out okay!

**Comment by monfresh** [comment]
Thanks, @nates-r7! I'm trying to figure out why RVM is not installing Ruby anymore.

**Comment by monfresh** [comment]
Also, are you on Mavericks or Yosemite, @nates-r7 ?

**Comment by nates-r7** [comment]
10.10.3. brand new 4 hour old install. Had previously installed xcode and sublime 2, nothing else.

**Comment by monfresh** [comment]
It turns out that adding the `--with-gems="bundler"` flag to the initial RVM installation is what was causing the problem. I've removed it, and the script should work as it did before.
