### ISSUE TITLE
Script fails when not retrieving latest version

### ISSUE THREAD

**Issue by IPconfig** [monfresh/laptop#9]
Brand new installation of OS X (10.10.3)
First time I run the script, it completely finished. (Saves me a lot of time, thanks for this!)
Second time I run the script, it failed after hub. Probably because it could not get the the latest version available of RVM
```
Homebrew already installed. Skipping ...

Updating Homebrew formulas ...
Already up-to-date.

Already using the latest version of git. Skipping ...

Already using the latest version of postgresql. Skipping ...

Restarting postgres...
Stopping `postgresql`... (might take a while)
==> Successfully stopped `postgresql` (label: homebrew.mxcl.postgresql)
==> Successfully started `postgresql` (label: homebrew.mxcl.postgresql)

Already using the latest version of qt. Skipping ...

Already using the latest version of hub. Skipping ...
failed
```
This could be handled better to indicate that people should run the script again or check their internet connection to progress further.

**Comment by monfresh** [comment]
Thanks for the report. Did you quit and relaunch Terminal in between the first and second runs? If not, could you try that and see if you are able to run the script again?

**Comment by IPconfig** [comment]
I did close the terminal between runs. I ran the script again after the failure, and it proceeded till the end. Must be a problem with my internet connection that caused it to fail.
It just sparkled some confusion because I didn't know if everything installed correctly (It did!)
